DAM-1: Estrutura inicial
Phill-Andrade/damas pull request #1
Opened 2021-07-16 21:24 UTC by eduardoKatsurayama

**Tarefa:**

[DAM-1](https://eduardokatsurayama.atlassian.net/browse/DAM-1)

**Checklist da tarefa:**

- [x] Criada a estrutura de diretórios.
- [x] Atualizado README.md.
- [x] Adicionado sistema CHANGELOG.md.
- [x] Adicionada a estrutura de testes.

2021-07-16 21:30 UTC, Phill-Andrade requested changes

2021-07-16 21:30 UTC, Phill-Andrade commented on requirements/prod.txt
> +flake8==3.8.4
Essas libs não seriam melhores no requirements/dev ?

2021-07-16 21:32 UTC, eduardoKatsurayama commented on requirements/prod.txt
> +flake8==3.8.4
trocados para dev.txt!

2021-07-16 21:33 UTC, Phill-Andrade approved these changes

2021-07-20 00:50 UTC, daanilol approved these changes

2021-07-20 00:51 UTC, merged